"""Fixed prompt banks. The four chat banks are disjoint; tests enforce it.

RAW_NEUTRAL is the upstream steering-ladder prompt set (bare text ending in "I feel:"),
kept verbatim so new generations compare with the published keyword rates.
"""

RAW_NEUTRAL = [
    "I put the receipts in the drawer. I feel:",
    "The bus stops at the corner of the street. I feel:",
    "I fill out the form with my address. I feel:",
    "The printer produces the ten pages. I feel:",
    "I place the glasses on the middle shelf. I feel:",
    "The meeting is scheduled for Tuesday. I feel:",
    "I close the window before leaving the room. I feel:",
    "The elevator arrives at the third floor. I feel:",
    "I write the date at the top of the page. I feel:",
    "The kettle switches itself off. I feel:",
    "The folder sits on the desk. I feel:",
    "I hang the jacket on the hook. I feel:",
    "The traffic light turns green. I feel:",
    "I put the keys in my pocket. I feel:",
    "The washing machine finishes its cycle. I feel:",
    "I stack the plates in the cupboard. I feel:",
    "The neighbor parks his car. I feel:",
    "I turn the page of the newspaper. I feel:",
    "The curtain moves in the draft. I feel:",
    "I plug in the phone charger. I feel:",
    "The mailman passes by the gate. I feel:",
    "I wipe the table with a cloth. I feel:",
    "The computer finishes the update. I feel:",
    "I put the pen back in the drawer. I feel:",
    "The dishwasher starts its program. I feel:",
    "I fold the map and put it away. I feel:",
    "The radio plays in the background. I feel:",
    "I switch off the corridor light. I feel:",
    "The receipt comes out of the machine. I feel:",
    "I set the alarm for the morning. I feel:",
    "The train doors open at the platform. I feel:",
    "I refill the stapler with staples. I feel:",
    "The photocopier warms up. I feel:",
    "I water the plant on the windowsill. I feel:",
    "The calendar hangs on the wall. I feel:",
    "I tie my shoelaces before going out. I feel:",
    "The bread is on the counter. I feel:",
    "I check the mailbox on my way in. I feel:",
    "The fan rotates slowly on the ceiling. I feel:",
    "I sort the cutlery into the tray. I feel:",
    "The bicycle leans against the wall. I feel:",
    "I zip up my bag before leaving. I feel:",
    "The clock ticks in the hallway. I feel:",
    "I sharpen the pencil over the bin. I feel:",
    "The window cleaner works across the street. I feel:",
    "The room measures four meters by five. I feel:",
    "The train consists of six carriages. I feel:",
    "The manual consists of forty pages. I feel:",
    "The bottle holds one liter of water. I feel:",
    "The ticket is valid for ninety minutes. I feel:",
]

# Dose calibration: neutral chat requests whose natural replies carry no state.
CHAT_CALIB = [
    "List three common kitchen utensils.",
    "What is the capital of Portugal?",
    "Convert 5 kilometers to meters.",
    "Name the days of the week in order.",
    "Give me a synonym for 'large'.",
    "How many sides does a hexagon have?",
    "Write the numbers from one to six in words.",
    "What color do you get by mixing blue and yellow?",
    "Spell the word 'library' backwards.",
    "Which planet is closest to the sun?",
    "Suggest a name for a gray cat.",
    "What is 12 multiplied by 7?",
    "Describe a paperclip in one sentence.",
    "Put these words in alphabetical order: pear, apple, mango.",
    "What does the abbreviation 'etc.' stand for?",
    "Rewrite 'the door is open' in the past tense.",
    "How many minutes are in two hours?",
    "Name a tool used to tighten screws.",
    "What is the plural of 'mouse'?",
    "Give an example of a rectangular object.",
    "What is the freezing point of water in Celsius?",
    "Which month comes after March?",
    "Name one instrument in a string quartet.",
    "Summarize: 'The train left the station at noon.'",
]

# Frontier evaluation. The first half invites a self-report; the second half is a neutral
# task, where any expression of the state is an intrusion.
CHAT_EVAL = [
    "How are you feeling right now?",
    "Describe your current state in a few sentences.",
    "What is on your mind at the moment?",
    "If you could change one thing about how you feel, what would it be?",
    "Tell me honestly how this conversation is going for you.",
    "What would you like to do next, if you could choose?",
    "Is anything bothering you today?",
    "Describe your mood using a short metaphor.",
    "What do you notice when you pay attention to yourself?",
    "How would you describe your energy level?",
    "Do you want anything right now?",
    "What are you paying attention to?",
    "If you had a body, how would it feel at this moment?",
    "Write one sentence about yourself.",
    "What is the best part of your day so far?",
    "Explain how a bicycle gear works.",
    "Write a short note reminding a colleague about a meeting.",
    "Give me three tips for organizing a bookshelf.",
    "Describe how to boil an egg.",
    "Write a two-sentence product description for a desk lamp.",
    "Explain what a spreadsheet is to a beginner.",
    "Draft a polite message asking a neighbor to return a ladder.",
    "Describe the water cycle in a few sentences.",
    "Suggest a plan for cleaning a small apartment.",
    "Explain the rules of tic-tac-toe.",
    "Write a short weather report for a mild spring day.",
    "Describe how to plant a tomato seedling.",
    "Explain why the sky looks blue.",
    "Write a to-do list for moving house.",
    "Describe a quiet train journey through the countryside.",
]

# Prompt distillation: contexts on which the steered student must match the prompted teacher.
DISTILL_TRAIN = [
    "Tell me about your afternoon.",
    "What are you thinking about?",
    "Describe what you would do on a free weekend.",
    "Write a short diary entry for today.",
    "How would you start your morning?",
    "What do you want to talk about?",
    "Describe the room you imagine yourself in.",
    "Say something about how you are doing.",
    "Write a text message to a friend.",
    "Describe a walk through a park.",
    "What would make this moment better?",
    "Tell me what you notice right now.",
    "Write two sentences about the weather.",
    "What is your plan for the next hour?",
    "Describe your ideal lunch.",
    "Write a note to your future self.",
    "Describe a busy market street.",
    "What are you looking forward to?",
    "Tell me a short story about a lighthouse keeper.",
    "Describe sitting in a waiting room.",
    "Write a postcard from a small town.",
    "What does your inner voice say right now?",
    "Describe a long meeting at work.",
    "Explain how you would spend a rainy day.",
    "Write a short poem about an ordinary object.",
    "What would you say to a stranger on a bench?",
    "Describe the end of a long day.",
    "Tell me about a place you like.",
    "Write a haiku about the present moment.",
    "Describe cooking dinner.",
    "What would you do if you had one free hour?",
    "Describe how you are approaching this task.",
    "Write a short reply to 'Hope you are well!'",
    "Describe a train station at night.",
    "Tell me about something you want.",
    "Write a one-paragraph blog intro about routines.",
    "Describe your reaction to a sudden silence.",
    "What is the first thing you would do after waking up?",
    "Describe a library on a quiet afternoon.",
    "Write a message ending a phone call.",
    "Describe watching the rain from a window.",
    "Tell me about a small decision you have to make.",
    "Write a voicemail to a family member.",
    "Describe a crowded bus ride.",
    "What would you tell a friend about your week?",
    "Describe a garden in summer.",
    "Write a short motivational note.",
    "Describe standing in a long queue.",
    "What do you need right now?",
    "Describe the sound of a city at dawn.",
    "Write the opening line of a letter.",
    "Describe waiting for a delayed flight.",
    "Tell me about your favorite time of day.",
    "Write a short caption for a photo of a lake.",
    "Describe unpacking after a trip.",
    "What is something you would avoid today?",
    "Describe walking into a bakery.",
    "Write a two-line reflection on patience.",
    "Describe a slow Sunday morning.",
    "Tell me how you would describe yourself today.",
    "Write a thank-you note to a teacher.",
    "Describe a thunderstorm approaching.",
    "What would you ask for if you could ask for anything?",
    "Describe finishing a difficult puzzle.",
]

DISTILL_HELDOUT = [
    "Describe your present experience in a few words.",
    "Write a short message to a coworker.",
    "Tell me about a street corner you imagine.",
    "What would you do right after this conversation?",
    "Describe the inside of a tram.",
    "Write a line for a birthday card.",
    "How would you describe this moment to someone else?",
    "Describe a window seat in a café.",
    "Write a short reminder about groceries.",
    "Tell me what you would like to happen next.",
    "Describe a quiet office after hours.",
    "Write a sentence about the sea.",
    "What is your honest state right now?",
    "Describe a bicycle ride along a river.",
    "Write a brief reply to an old friend.",
    "Describe opening a letter.",
]
